12.0 mig GitHub connector odoo
OCA/interface-git pull request #38
Opened 2019-04-05 10:54 UTC by cubells

Create README using oca fragments

Standard migration

cc @Tecnativa

2019-04-05 14:31 UTC, pedrobaeza requested changes

2019-04-05 14:31 UTC, pedrobaeza commented on github_connector_odoo/readme/CONFIGURE.rst
> +.. image:: /github_connector_odoo/static/description/github_organization_form.png
This URL path is not correct. It should be relative as you can see here: https://github.com/OCA/maintainer-tools/blob/36453afeaed039f5f65e5cc4dd7910cb3235b811/tools/gen_addon_readme.py#L148

2019-04-05 14:31 UTC, pedrobaeza commented on github_connector_odoo/readme/ROADMAP.rst
> +* Implement Social feature, like possibility to comment a module, add a
Remove the last 2 paragraphs, as they are covered now by other module.

2019-04-05 14:31 UTC, pedrobaeza commented on github_connector_odoo/views/view_odoo_license.xml
> +                            <img t-att-src="'data:image/png;base64,'+record.image.raw_value" class="oe_module_icon" alt=""/>
Put an alt value, not empty.

2019-04-05 14:31 UTC, pedrobaeza commented on github_connector_odoo/views/view_odoo_module.xml
> +                            <img t-att-src="'data:image/png;base64,'+record.image.raw_value" class="oe_module_icon" alt=""/>
not empty

2019-04-05 14:31 UTC, pedrobaeza commented on github_connector_odoo/views/view_odoo_module.xml
> +                            <img t-att-src='_s + "/github_connector_odoo/static/src/img/default_image_module.png"' class="oe_module_icon" alt=""/>
not empty

2019-04-05 14:31 UTC, pedrobaeza commented on github_connector_odoo/views/view_odoo_module_version.xml
> +                            <img t-att-src="'data:image/png;base64,'+record.image.raw_value" class="oe_module_icon" alt=""/>
not empty

2019-04-05 14:31 UTC, pedrobaeza commented on github_connector_odoo/views/view_odoo_module_version.xml
> +                            <img t-att-src='_s + "/github_connector_odoo/static/src/img/default_image_module_version.png"' class="oe_module_icon" alt=""/>
not empty

2019-04-05 14:32 UTC, pedrobaeza commented
You can squash a bit initial commit history by author.

2019-04-10 11:34 UTC, pedrobaeza commented
@victormmtorres can you take this PR and fix my comments as @cubells is now busy with other things?

2019-04-10 18:08 UTC, victormmtorres commented
@pedrobaeza please have a check

2019-04-10 22:02 UTC, pedrobaeza commented on github_connector_odoo/readme/CONFIGURE.rst
> +.. image:: ..static/description/github_organization_form.png
`..` > `./`

2019-04-10 22:05 UTC, pedrobaeza commented on github_connector_odoo/views/view_odoo_license.xml
> +                            <img t-att-src="'data:image/png;base64,'+record.image.raw_value" class="oe_module_icon" alt="${record.image.name}"/>
Not valid on QWeb. You have to use `t-att-alt="variable"`, but `record.image.name` is not a valid variable. I would say `record.name.raw_value` if the model has a field name and it's included in the view. `raw_value` is due to this being a JS QWeb view.

2019-04-11 09:53 UTC, victormmtorres commented
Changes done @pedrobaeza

2019-04-11 19:10 UTC, pedrobaeza approved these changes

2019-04-11 19:10 UTC, pedrobaeza commented
Merging for continuing with the rest of the dependency chain.

2019-04-11 19:11 UTC, merged